MEMBER_ROLE_ID = 3
REFINERY_ROLE_ID = 2
SUPERUSER_ROLE_ID = 1

module Provinces
  CODES = %w(AB BC MB NB NL NT NS NU ON PE QC SK YT --
    AK AL AR AS AZ CA CO CT DC DE FL FM GA GU HI IA ID
    IL IN KS KY LA MA ME MD MH MI MN MO MP MS MT NC ND
    NE NH NJ NM NV NY OH OK OR PA PR PW RI SC SD TN TX
    UT VI VT VA WA WI WV WY)
end